objects/Contact/fields/Height_Feet__c.field-meta.xml
<CustomField>
    <fullName>Height_Feet__c</fullName>
    <description>The number of whole feet. For example if a player&apos;s height is 6&apos;8&quot;, this number will be 6.</description>
    <label>Height Feet</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Contact/fields/Height_Inches__c.field-meta.xml
<CustomField>
    <fullName>Height_Inches__c</fullName>
    <description>The number of whole feet. For example if a player&apos;s height is 6&apos;8&quot;, this number will be 8.</description>
    <inlineHelpText>The number of whole feet. For example if a player&apos;s height is 6&apos;8&quot;, this number will be 8.</inlineHelpText>
    <label>Height Inches</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>C = Center, PF = Power Forward, SF = Small Forward, SG = Shooting Guard, PG = Point Guard, G = Guard, F = Forward.</description>
    <inlineHelpText>C = Center, PF = Power Forward, SF = Small Forward, SG = Shooting Guard, PG = Point Guard, G = Guard, F = Forward.</inlineHelpText>
    <label>Position</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

objects/Contact/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

classes/PlayerController.cls
public class PlayerController {

    //Variables for binding
    public List<Contact> playerList{get;set;}
    public String searchName{get;set;}
    public String seasonYear{get;set;}
    
    //generate search results list of players
    public void generatePlayerList()
    {
         	
		playerList = [SELECT Name, Weight__c, Height_Feet__c, Height_Inches__c,Position__c FROM Contact WHERE name =:searchName ];
    }
    
    
}